


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/openAi?currentSchema=chat
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    maximum-pool-size: 10
    minimum-idle: 5




mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.chat.chatopenai.entity
  global-config:
    db-config:
      id-type: ASSIGN_ID
      select-strategy: ignored
      insert-strategy: ignored
      update-strategy: not_null
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

---
server:
  port: 9000
spring:
  elasticsearch:
    uris: http://124.220.25.5:9200
