

server:
  port: 9000
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/openAi?currentSchema=chat
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
#    maximum-pool-size: 10
#    minimum-idle: 5
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://192.168.3.188:3306/chat?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: MyHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
---
spring:
  elasticsearch:
    uris: http://124.220.25.5:9200


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.chat.auth.entity
  global-config:
    db-config:
      id-type: auto
      select-strategy: ignored
      insert-strategy: ignored
      update-strategy: not_null
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true


